services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slotegrator_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      APP_ENV: dev
    networks:
      - slotegrator_network

  database:
    image: postgres:13
    container_name: slotegrator_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: slotegrator_user
      POSTGRES_PASSWORD: slotegrator_secret
      POSTGRES_DB: slotegrator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - slotegrator_network

  nginx:
    image: nginx:latest
    container_name: slotegrator_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - slotegrator_network

volumes:
  postgres_data:

networks:
  slotegrator_network:
    driver: bridge